### ISSUE TITLE
plotenvelope does not work with offsets

### ISSUE THREAD

**Issue by gordy2x** [eco-stats/ecostats#1]
data(reveg)
Acarina_dat <- with( reveg, data.frame(Acarina  = abund$Acarina ,
                              pitfalls = pitfalls,
                              treatment = treatment))

ft.crab <- glm(Acarina  ~ treatment + offset(log(pitfalls)), family = poisson(), data = Acarina_dat)
> plotenvelope(ft.crab)
Error in eval(predvars, data, env) : object 'pitfalls' not found

**Comment by dwarton** [comment]
this would have worked if you used
`ft.crab <- glm(Acarina ~ treatment, offset=log(pitfalls), family = poisson(), data = Acarina_dat)`
but [v1.1.12](https://github.com/eco-stats/ecostats/commit/89359aac838c9dd652223c47adaa9ca67041b125) now also accepts offsets in formulas... I think
