### ISSUE TITLE
Error with glmmTMB

### ISSUE THREAD

**Issue by gordy2x** [eco-stats/ecostats#3]
> rich_mod <- glmmTMB(Richness ~ Mod  + (1|Estuary), family = poisson(), data = estuaries)
> rich_mod_0 <- glmmTMB(Richness ~ 1 + (1|Estuary), family = poisson(), data = estuaries) 
> anovaPB(rich_mod_0, rich_mod, n.sim = 100)
Warning in Ops.factor(1, Estuary) : ‘|’ not meaningful for factors
Error in `[[<-.data.frame`(`*tmp*`, 1, value = c(2, 2, 5, 6, 6, 7, 4,  : 
  replacement has 42 rows, data has 0

**Comment by dwarton** [comment]
I think this has been fixed as of v 1.1.14 but it's Friday evening and my laptop seems to have already started its weekend so only 90% confident
